{% set version = "3.0.9" %}
{% set sha256 = "0b0ca6514430e2cf87ea4c9148e744919dbd9b6e35c3ef1dc6c12faefe8891ae" %}

package:
  name: ncbi-amr
  version: {{ version }}

source:
  url: https://github.com/ncbi/amr/archive/amrfinder_v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - compile-fix.patch

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - coreutils
  run:
    - blast
    - hmmer
    - perl

test:
  commands:
    - amr_report -h
    - fasta_check -h
    - gff_check -h
    - amrfinder.pl -h

about:
  home: https://github.com/ncbi/amr/wiki
  license: Public Domain
  license_file: LICENSE
  summary: AMRFinder find acquired antimicrobial resistance genes in protein or nucleotide sequences.

