
package:
  name: libsequence
  version: '1.9.8'

source:
  url: https://github.com/molpopgen/libsequence/archive/1.9.8.tar.gz
  sha256: 16c3ff6490861806292391195a8698fc17f4d5d30cbe3f5e5e1de1a03d1105f8

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - boost >=1.60.0

test:
  commands:
    - libsequenceConfig --version | grep 1.9.7 > /dev/null

about:
  home: http://http://molpopgen.github.io/libsequence/
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: 'A C++ class library for evolutionary genetics.'
