package:
  name: galaxy-parsec
  version: "1.12.1"

source:
  url: https://files.pythonhosted.org/packages/79/22/26a2b7205f11ae5da55ed6e3bb7eb5b29f5eb84cd1055f08e062b7cb4b68/galaxy-parsec-1.12.1.tar.gz
  sha256: 00b87472aa06b6da3450be215125bb8361ee5c9f654fa080ad8389811f04a1c4

build:
  noarch: python
  # noarch: python
  preserve_egg_dir: True
  entry_points:
    - parsec=parsec.cli:parsec
  number: 0

requirements:
  host:
    - python
    - setuptools
    - click >=6.7
    - bioblend
    - wrapt
    - pyyaml
    - justbackoff
    - xunit-wrapper
    - future

  run:
    - python
    - click >=6.7
    - bioblend
    - wrapt
    - pyyaml
    - justbackoff
    - xunit-wrapper >=0.12
    - future

extra:
  container:
    extended-base: true

test:
  imports:
    - parsec
    - parsec.commands
    - parsec.commands.config
    - parsec.commands.datasets
    - parsec.commands.datatypes
    - parsec.commands.folders
    - parsec.commands.forms
    - parsec.commands.ftpfiles
    - parsec.commands.genomes
    - parsec.commands.groups
    - parsec.commands.histories
    - parsec.commands.jobs
    - parsec.commands.libraries
    - parsec.commands.quotas
    - parsec.commands.roles
    - parsec.commands.tool_data
    - parsec.commands.tools
    - parsec.commands.toolshed
    - parsec.commands.toolshed_categories
    - parsec.commands.toolshed_repositories
    - parsec.commands.toolshed_tools
    - parsec.commands.users
    - parsec.commands.utils
    - parsec.commands.visual
    - parsec.commands.workflows

  commands:
    - parsec --help

about:
  home: https://github.com/galaxy-iuc/parsec
  license: MIT
  summary: 'Command-line utilities to assist in interacting with Galaxy servers (http://galaxyproject.org/).'
  license_family: MIT
